apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
        - name: client
          image: ghcr.io/ralikio/images/client:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure