apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
    - image: ghcr.io/ralikio/images/app:latest
      name: app
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
